"""
ticket_client.py
Handles loading ticket data from JSON and writing triage notes to output files.

Future: Integrate with ServiceNow / Jira REST APIs.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field, field_validator

from tools.audit_logger import AuditLogger


# ── Ticket Schema ──────────────────────────────────────────────────────────────

class Ticket(BaseModel):
    """
    Pydantic v2 schema for incoming ticket JSON.
    All fields are validated on load.
    """
    ticket_id: str = Field(..., min_length=1, max_length=64)
    source: str = Field(default="unknown")
    severity: str = Field(default="Medium")
    alert: str = Field(..., min_length=1, max_length=256)
    device: str = Field(..., min_length=1, max_length=128)
    interface: Optional[str] = Field(default=None)
    ip: Optional[str] = Field(default=None)
    vlan: Optional[str] = Field(default=None)
    description: str = Field(default="")
    created_at: str = Field(default="")

    @field_validator("ticket_id")
    @classmethod
    def ticket_id_safe(cls, v: str) -> str:
        """Ensure ticket ID is filesystem-safe (no path traversal)."""
        import re
        if not re.match(r"^[A-Za-z0-9_\-]+$", v):
            raise ValueError(f"Ticket ID '{v}' contains invalid characters.")
        return v

    @field_validator("device")
    @classmethod
    def device_safe(cls, v: str) -> str:
        """Ensure device name is hostname-safe."""
        import re
        if not re.match(r"^[A-Za-z0-9_\-\.]+$", v):
            raise ValueError(f"Device name '{v}' contains invalid characters.")
        return v.lower()

    @field_validator("severity")
    @classmethod
    def severity_valid(cls, v: str) -> str:
        allowed = {"Critical", "High", "Medium", "Low", "Informational"}
        if v not in allowed:
            return "Medium"
        return v


# ── TicketClient ───────────────────────────────────────────────────────────────

class TicketClient:
    """
    Loads tickets from JSON files.
    Writes triage notes to the outputs/ directory.
    Future: ServiceNow / Jira integration.
    """

    def __init__(
        self,
        outputs_dir: str = "outputs/",
        audit_logger: Optional[AuditLogger] = None,
    ):
        self.outputs_dir = Path(outputs_dir)
        self.outputs_dir.mkdir(parents=True, exist_ok=True)
        self.audit = audit_logger or AuditLogger()

    def load_ticket(self, path: str) -> Ticket:
        """Load and validate a ticket from a JSON file."""
        fpath = Path(path)
        if not fpath.exists():
            raise FileNotFoundError(f"Ticket file not found: {path}")

        with open(fpath, encoding="utf-8") as f:
            data = json.load(f)

        ticket = Ticket(**data)
        self.audit.ticket_loaded(
            ticket_id=ticket.ticket_id,
            source=ticket.source,
            alert=ticket.alert,
            device=ticket.device,
        )
        return ticket

    def save_triage_note(self, ticket_id: str, note: str) -> str:
        """
        Save triage note to outputs/triage_note_<ticket_id>.txt
        Returns the output file path.
        """
        # Sanitize ticket_id for filesystem use (already validated by Pydantic)
        filename = f"triage_note_{ticket_id}.txt"
        output_path = self.outputs_dir / filename

        header = (
            f"{'=' * 60}\n"
            f"NOC AI PRE-TRIAGE NOTE\n"
            f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
            f"Ticket: {ticket_id}\n"
            f"{'=' * 60}\n\n"
        )

        full_content = header + note + "\n\n" + (
            "=" * 60 + "\n"
            "END OF AI PRE-TRIAGE NOTE\n"
            "This note was generated by an automated read-only AI agent.\n"
            "All findings must be verified by a qualified network engineer.\n"
            "No changes were made to any device.\n"
            "=" * 60 + "\n"
        )

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(full_content)

        self.audit.triage_note_generated(
            output_path=str(output_path),
            note_length=len(full_content),
        )

        return str(output_path)

    def format_ticket_summary(self, ticket: Ticket) -> str:
        """Format ticket fields into a clean summary string for the LLM prompt."""
        lines = [
            f"Ticket ID: {ticket.ticket_id}",
            f"Source: {ticket.source}",
            f"Alert: {ticket.alert}",
            f"Severity: {ticket.severity}",
            f"Device: {ticket.device}",
        ]
        if ticket.interface:
            lines.append(f"Interface: {ticket.interface}")
        if ticket.ip:
            lines.append(f"IP: {ticket.ip}")
        if ticket.vlan:
            lines.append(f"VLAN: {ticket.vlan}")
        if ticket.description:
            lines.append(f"Description: {ticket.description}")
        if ticket.created_at:
            lines.append(f"Created At: {ticket.created_at}")
        return "\n".join(lines)
